version: "3"
services:
  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/home/jovyan/work
    links:
      - postgres
  postgres:
    image: postgres:11.6
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
